In [43]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pickle

## Data for squeezing and erosion instablity

In [35]:
data = pd.read_csv('2cmCarpet.csv') ## Data for squeezing and erosion instabilities obtained from video recordings.
## Data contains Discharge [Q], water depth [depth], flow velocity [velocity], carpet length [Length], and
## Boolean values for [squeeze] and [erode].
data.head()

    Q (l/s)  depth (cm)  velocity (m/s)  Length (m)  squeeze  erode
0  12.53279     15.0740          0.2079        0.50        1      0
1  10.42890     14.8484          0.1756        0.75        1      0
2  12.97240     15.2620          0.2125        0.75        1      0
3   9.64390     14.6604          0.1645        1.00        1      0
4   9.83240     14.7732          0.1664        1.00        1      0

## Data for velocity measurement using Laser Doppler Anemometry (LDA)

In [ ]:
with open('2_00meterCarpet.pickle', 'rb') as f: ### Loading the experimental data
        dataList = pickle.load(f)

In [29]:
## Change index [0] of dataList to other numbers for retriving the data at other positions. Index [0] indicates the position of far downstream.
dataList[0].head() ## -> time series data at position [0] for water levels [WaterLevel1, WaterLevel2, WaterLevel3] 
            ## for three different positions, vertical position of LDA system [DisplacementLDA], 
            ## discharge [FlowRate], and two components of LDA measurement [Vel1, Vel2]
## Please consult the "DescriptionDataStability.pdf" for more information, e.g. calibration parameters.

,Date,Time,WaterLevel1 [v],WaterLevel2 [V],WaterLevel3 [V],DisplacementLDA [V],FlowRate [volt],Vel1 [V],Vel2 [V],Unnamed: 9
0,20-4-2023,11:48:46.000,6.9964,7.0916,6.5246,6.1,3.9153,-0.1463,0.2980,NaN
1,20-4-2023,11:48:46.001,6.9924,7.0910,6.5246,6.1,3.9223,-0.1579,0.2950,NaN
2,20-4-2023,11:48:46.002,6.9918,7.0910,6.5246,6.1,3.9278,-0.1738,0.3130,NaN
3,20-4-2023,11:48:46.003,6.9778,7.0910,6.5252,6.1,3.9260,-0.1418,0.2858,NaN
4,20-4-2023,11:48:46.004,7.0019,7.0919,6.5179,6.1,3.9168,-0.1213,0.2571,NaN